@startuml Payle

package "API Gateway" {
    component [Kong API Gateway]
}

package "Microservices" {
    component [Authentication Service]
    component [Store Management Service]
    component [Financial Service]
    component [Product Catalog Service]
    component [Customer Management Service]
    component [Communication Service]
    component [Checkout Service]
    component [Subscription Service]
    component [Payment Processing Service]
}

database "Databases" {
    [Auth DB]
    [Store DB]
    [Financial DB]
    [Product DB]
    [Customer DB]
    [Communication DB]
    [Checkout DB]
    [Subscription DB]
    [Payment DB]
}

node "Messaging" {
    [Kafka]
}

actor "Web Client (React App)"
actor "External API Consumer"

Kong_API_Gateway --> [Authentication Service]
Kong_API_Gateway --> [Store Management Service]
Kong_API_Gateway --> [Financial Service]
Kong_API_Gateway --> [Product Catalog Service]
Kong_API_Gateway --> [Customer Management Service]
Kong_API_Gateway --> [Communication Service]
Kong_API_Gateway --> [Checkout Service]
Kong_API_Gateway --> [Subscription Service]
Kong_API_Gateway --> [Payment Processing Service]

[Authentication Service] --> [Auth DB]
[Store Management Service] --> [Store DB]
[Financial Service] --> [Financial DB]
[Product Catalog Service] --> [Product DB]
[Customer Management Service] --> [Customer DB]
[Communication Service] --> [Communication DB]
[Checkout Service] --> [Checkout DB]
[Subscription Service] --> [Subscription DB]
[Payment Processing Service] --> [Payment DB]

"Web Client (React App)" --> Kong_API_Gateway
"External API Consumer" --> Kong_API_Gateway

[Store Management Service] ..> Kafka
[Financial Service] ..> Kafka
[Product Catalog Service] ..> Kafka
[Communication Service] ..> Kafka

@enduml
